DROP TABLE IF EXISTS comments, comments_moderate;

CREATE TABLE comments
(
    id SERIAL PRIMARY KEY,
    NEWS_ID INTEGER NOT NULL,
    AUTHOR TEXT NOT NULL,
    PARENT_ID INTEGER NOT NULL,
    CONTENT TEXT NOT NULL
);

CREATE TABLE comments_on_moderate
(
    id SERIAL PRIMARY KEY,
    NEWS_ID INTEGER NOT NULL,
    AUTHOR TEXT NOT NULL,
    PARENT_ID INTEGER NOT NULL,
    CONTENT TEXT NOT NULL,
    BAD BOOLEAN,
    BAD_REASON TEXT
);